### ISSUE TITLE
when().method(anyInt()) и подобные

### ISSUE THREAD

**Issue by nixel2007** [nixel2007/moskito#2]

**Comment by artbear** [comment]
@nixel2007 Маленькое ура в связи с поддержкой Делегатов ? :)

**Comment by nixel2007** [comment]
@artbear угу) их обрабатывать было проще. Но я планирую добавить поддержку и описаний оповещения. А потом можно перетащить во fluent

**Comment by asosnoviy** [comment]
А тут чего нехватает для счастья?

**Comment by nixel2007** [comment]
Документации
