### ISSUE TITLE
OPM при установке библиотеки moskito, устанавливает не все зависимости.

### ISSUE THREAD

**Issue by mity1982** [nixel2007/moskito#32]
Не устанавливается logos, notify.

**Comment by nixel2007** [comment]
Это странно, т.к. эти зависимости должны транзитивно выкачиваться. Например, fluent зависит от notify.

Можно полный лог установки?

**Comment by nixel2007** [comment]
и версию opm

**Comment by mity1982** [comment]
Версию opm не знаю как посмотреть. oscript - 1.4 .

Я косякнул. В проекте используется локальный (для проекта) набор
библиотек и поскольку, при установке moskito, не упоминаются logos, notify (они уже были установлены), то я их не перенес в локальную папку библиотек. Проверил сейчас, если библиотек  logos, notify нет, то они устанавливаются. 

C:\Windows\system32>opm install moskito
ИНФОРМАЦИЯ - Скачиваю файл: moskito.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет moskito
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: asserts
ИНФОРМАЦИЯ - asserts уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: delegate
ИНФОРМАЦИЯ - delegate уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: fluent
ИНФОРМАЦИЯ - fluent уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - strings уже установлен. Пропускаем.

----------------

C:\Windows\system32>opm install moskito
ИНФОРМАЦИЯ - Скачиваю файл: moskito.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет moskito
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: asserts
ИНФОРМАЦИЯ - Скачиваю файл: asserts.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет asserts
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: delegate
ИНФОРМАЦИЯ - Скачиваю файл: delegate.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет delegate
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - Скачиваю файл: logos-0.6.2.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет logos
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: fluent
ИНФОРМАЦИЯ - Скачиваю файл: fluent.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет fluent
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: logos
ИНФОРМАЦИЯ - logos уже установлен. Пропускаем.
ИНФОРМАЦИЯ - Устанавливаю зависимость: notify
ИНФОРМАЦИЯ - Скачиваю файл: notify-0.2.0.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет notify
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - Скачиваю файл: strings.ospx
ИНФОРМАЦИЯ - Устанавливаю пакет strings
ИНФОРМАЦИЯ - Установка завершена
ИНФОРМАЦИЯ - Устанавливаю зависимость: strings
ИНФОРМАЦИЯ - strings уже установлен. Пропускаем.

**Comment by nixel2007** [comment]
оффтопик:

рекомендую посмотреть в сторону:
* `opm install -l`
* https://github.com/oscript-library/ovm
